"""removed api_key column from table UserModel

Revision ID: 1407d288e111
Revises: 09fd03ae191b
Create Date: 2022-04-20 20:18:50.324166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1407d288e111'
down_revision = '09fd03ae191b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
